# Generated by Django 5.2.7 on 2026-04-28 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_type', models.CharField(choices=[('YearlyContribution', 'Contributions'), ('mass_intention', 'Mass Intentions'), ('mixed', 'Mixed')], max_length=20)),
                ('approved_by', models.CharField(max_length=100)),
                ('approved_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('record_count', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'approval_batches',
                'ordering': ['-approved_at'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='approvals.approvalbatch')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'db_table': 'approval_items',
                'unique_together': {('content_type', 'object_id')},
            },
        ),
    ]
