# Generated by Django 5.2.7 on 2026-04-29 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approvalbatch',
            name='record_count',
        ),
        migrations.RemoveField(
            model_name='approvalbatch',
            name='total_amount',
        ),
        migrations.DeleteModel(
            name='ApprovalItem',
        ),
    ]
