# Generated by Django 5.2.7 on 2026-04-29 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0002_remove_approvalbatch_record_count_and_more'),
        ('mass_intentions', '0004_massintentionapprovalbatch_alter_massintention_batch'),
        ('yearly_contributions', '0005_yearlycontributionapprovalbatch_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApprovalBatch',
        ),
    ]
