# Generated by Django 5.2.7 on 2026-04-28 20:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MassIntention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mass_date', models.DateField()),
                ('concerned_names', models.CharField(help_text="Can be individual, group, or anonymous (e.g., 'The Choir', 'Mr and Mrs Obi')", max_length=500)),
                ('intention_text', models.TextField()),
                ('intention_type', models.CharField(choices=[('regular', 'Regular Intention'), ('thanksgiving', 'Open Thanksgiving')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(500)])),
                ('number_of_days', models.IntegerField(default=1, help_text='Calculated for regular intentions')),
                ('is_approved', models.BooleanField(default=False)),
                ('approved_by', models.CharField(blank=True, max_length=100, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'mass_intentions',
                'ordering': ['mass_date', '-created_at'],
                'indexes': [models.Index(fields=['mass_date'], name='mass_intent_mass_da_5405f3_idx'), models.Index(fields=['intention_type'], name='mass_intent_intenti_85b620_idx')],
            },
        ),
    ]
