# Generated by Django 5.2.7 on 2026-04-29 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mass_intentions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='massintention',
            name='mark_for_approval',
        ),
    ]
