# Generated by Django 5.2.7 on 2026-04-29 23:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0002_remove_approvalbatch_record_count_and_more'),
        ('mass_intentions', '0002_remove_massintention_mark_for_approval'),
    ]

    operations = [
        migrations.RenameField(
            model_name='massintention',
            old_name='amount',
            new_name='amount_paid',
        ),
        migrations.AddField(
            model_name='massintention',
            name='batch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_items', to='approvals.approvalbatch'),
        ),
    ]
