# Generated by Django 5.2.7 on 2026-05-01 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mass_intentions', '0005_alter_massintentionapprovalbatch_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='massintention',
            name='intention_type',
            field=models.CharField(choices=[('regular', 'Regular Intention'), ('thanksgiving', 'Open Thanksgiving'), ('both', 'Regular + Thanksgiving')], max_length=20),
        ),
        migrations.AlterField(
            model_name='massintention',
            name='number_of_days',
            field=models.IntegerField(default=1, help_text='Auto-calculated for regular intentions (1 day per ₦500)'),
        ),
    ]
