# Generated by Django 5.2.7 on 2026-05-13 21:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mass_intentions', '0006_alter_massintention_intention_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='massintention',
            name='end_date',
            field=models.DateField(blank=True, help_text='End date for regular intention announcements. Auto-calculated if not set.', null=True),
        ),
        migrations.AddField(
            model_name='massintention',
            name='mass_days',
            field=models.JSONField(blank=True, default=list, help_text='List of days when masses are held, e.g., [0, 6] for Sundays and Saturdays (0=Monday, 6=Sunday)'),
        ),
        migrations.AddField(
            model_name='massintention',
            name='thanksgiving_date',
            field=models.DateField(blank=True, help_text='Date for thanksgiving mass (usually Sunday). Required for thanksgiving/both types.', null=True),
        ),
        migrations.AlterField(
            model_name='massintention',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='mass_intentions.massintentionapprovalbatch'),
        ),
        migrations.AlterField(
            model_name='massintention',
            name='mass_date',
            field=models.DateField(help_text='Start date for the mass intention announcements'),
        ),
        migrations.AlterField(
            model_name='massintention',
            name='number_of_days',
            field=models.IntegerField(default=1, help_text='Number of mass days the intention will be announced'),
        ),
        migrations.AddIndex(
            model_name='massintention',
            index=models.Index(fields=['thanksgiving_date'], name='mass_intent_thanksg_cccbad_idx'),
        ),
    ]
