# Generated by Django 5.2.7 on 2026-06-04 00:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mass_intentions', '0007_massintention_end_date_massintention_mass_days_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='massintentionapprovalbatch',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='massintentionapprovalbatch',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_%(class)s_batches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='massintentionapprovalbatch',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='massintentionapprovalbatch',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='massintention',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='massintentionapprovalbatch',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='massintentionapprovalbatch',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_%(class)s_batches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='MassIntentionReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scheduled_date', models.DateField()),
                ('was_read', models.BooleanField(default=True)),
                ('skipped_reason', models.TextField(blank=True, help_text="e.g., 'Mass canceled due to holiday', 'Priest unavailable', 'Time constraints'")),
                ('mass_intention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='mass_intentions.massintention')),
                ('read_by', models.ForeignKey(blank=True, help_text='User who confirmed this reading (usually secretary or priest)', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mass_intention_readings',
                'ordering': ['scheduled_date'],
                'unique_together': {('mass_intention', 'scheduled_date')},
            },
        ),
    ]
