# Generated by Django 5.2.7 on 2026-06-04 00:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Church',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('weekday_mass_days', models.JSONField(blank=True, default=list, help_text='Days of week when masses are held')),
                ('name', models.CharField(help_text='Name of the church in the parish', max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='user',
            name='church',
            field=models.ForeignKey(blank=True, help_text='Only neccessary to associate secretary to a church in a parish', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.church'),
        ),
    ]
