# Generated by Django 5.2.7 on 2026-04-29 13:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='YearlyContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('mark_for_approval', models.BooleanField(default=False)),
                ('serial_number', models.CharField(max_length=50, unique=True)),
                ('payer_name', models.CharField(help_text='Can be individual or group name', max_length=255)),
                ('group_name', models.CharField(choices=[('men', 'Men'), ('women', 'Women'), ('youth', 'Youth'), ('children', 'Children')], max_length=20)),
                ('year', models.IntegerField()),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('recorder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'yearly_contributions',
                'ordering': ['-payment_date', '-created_at'],
                'indexes': [models.Index(fields=['year', 'group_name'], name='yearly_cont_year_d6e9c3_idx'), models.Index(fields=['payment_date'], name='yearly_cont_payment_4b93b2_idx'), models.Index(fields=['payer_name'], name='yearly_cont_payer_n_53749d_idx')],
            },
        ),
    ]
