# Generated by Django 5.2.7 on 2026-04-29 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yearly_contributions', '0002_remove_yearlycontribution_mark_for_approval'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yearlycontribution',
            name='serial_number',
        ),
    ]
