# Generated by Django 5.2.7 on 2026-04-29 23:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0002_remove_approvalbatch_record_count_and_more'),
        ('yearly_contributions', '0003_remove_yearlycontribution_serial_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='yearlycontribution',
            name='batch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_items', to='approvals.approvalbatch'),
        ),
    ]
