# Generated by Django 5.2.7 on 2026-04-30 14:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yearly_contributions', '0005_yearlycontributionapprovalbatch_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='yearlycontributionapprovalbatch',
            options={'ordering': ['-approved_at', '-created_at']},
        ),
        migrations.AddField(
            model_name='yearlycontributionapprovalbatch',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='yearlycontributionapprovalbatch',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
